version: '3'
services:
  redis:
    image: redis:latest
    container_name: "redis_S4G"
    command: redis-server
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: "always"


  se:
    build:
      context: ""
      dockerfile: Dockerfile
    image: garagon/simulation-engine
    container_name: "se"
    depends_on:
      - redis
    volumes:
       - ../simulation-engine/results:/usr/src/app/data
       #- C:/Program Files/OpenVPN/config:/usr/src/app/openvpn
       #- .:/usr/src/app
        #- host_path:${CONTAINER_PATH}#this in combination with the code below does not work on windows
        #- 'tests: /usr/src/app/tests'
    #network_mode: "host"
    ports:
        - "9090:9090"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    # restart: "always"
#    command: ["python3", "-u", "./profiles.py"]
    command: ["python3", "-u", "main.py"]
